/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Observador;

import static Observador.ClI.main;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import persistence.Persona;

/**
 *
 * @author Diaz
 */
public class ModificarDato extends javax.swing.JFrame implements Observador{

    /**
     * Creates new form AgregarDato
     */
    public ModificarDato() {
        initComponents();
    }
    public ModificarDato(Sujeto sujeto) {
        this.sujeto = sujeto;
                
        main(null);
        
        
        
    }
    public static Sujeto sujeto;
    public static int id1;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto1 = new javax.swing.JTextField();
        texto2 = new javax.swing.JTextField();
        RadioBoton1 = new javax.swing.JRadioButton();
        RadioBoton2 = new javax.swing.JRadioButton();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        Boton1 = new javax.swing.JButton();
        texto3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        RadioBoton1.setText("Conectado");
        RadioBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBoton1ActionPerformed(evt);
            }
        });

        RadioBoton2.setText("No Conectado");
        RadioBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBoton2ActionPerformed(evt);
            }
        });

        label2.setText("Nombre");

        label3.setText("Apellido");

        Boton1.setText("Aceptar");
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });

        texto3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                texto3KeyPressed(evt);
            }
        });

        jLabel1.setText("Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(label3)
                            .addGap(29, 29, 29)
                            .addComponent(texto2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(RadioBoton1)
                            .addGap(18, 18, 18)
                            .addComponent(RadioBoton2)))
                    .addComponent(Boton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(texto3)
                                .addComponent(texto1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioBoton1)
                    .addComponent(RadioBoton2))
                .addGap(18, 18, 18)
                .addComponent(Boton1)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
        // TODO add your handling code here:
        Persona p= new Persona();
        p.setId(Integer.parseInt(texto3.getText()));
        p.setNombre(texto1.getText());
        p.setApellido(texto2.getText());
        if(RadioBoton1.isSelected()){
            p.setConectado(true); 
        }
        if(RadioBoton2.isSelected()){
            p.setConectado(false); 
        }
        sujeto.Modificar(p);
        
    }//GEN-LAST:event_Boton1ActionPerformed

    private void RadioBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBoton1ActionPerformed
        // TODO add your handling code here:
        if(RadioBoton1.isSelected()){
            RadioBoton2.setSelected(false);
        }
    }//GEN-LAST:event_RadioBoton1ActionPerformed

    private void RadioBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBoton2ActionPerformed
        // TODO add your handling code here:
        if(RadioBoton2.isSelected()){
            RadioBoton1.setSelected(false);
        }
    }//GEN-LAST:event_RadioBoton2ActionPerformed

    private void texto3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texto3KeyPressed
        // TODO add your handling code here:
        int k = (int) evt.getKeyChar();//k = al valor de la tecla presionada
        boolean bool=true;

        if (k >= 97 && k <= 122 || k >= 65 && k <= 90) {//Si el caracter ingresado es una letra
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
            JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Validando Datos",
                    JOptionPane.ERROR_MESSAGE);
            texto3.setText("");
            texto3.requestFocus();
            bool=false;
        }

        if (k == 241 || k == 209) {//Si el caracter ingresado es una letra
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
            JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Validando Datos",
                    JOptionPane.ERROR_MESSAGE);
            texto3.setText("");
            texto3.requestFocus();
            bool=false;
        }
        
        if(bool&&texto3.getText().compareTo("")!=0){
            
        int n=Integer.parseInt(texto3.getText());
        
        if(n>sujeto.getEstado()&&n<0){
            JOptionPane.showMessageDialog(null, "No existe el id!!!", "INVALIDO",
                    JOptionPane.ERROR_MESSAGE);
            texto3.setText("");
            texto3.requestFocus();
            
        }
        }
    }//GEN-LAST:event_texto3KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarDato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarDato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarDato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarDato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarDato().setVisible(true);
                int id = sujeto.getEstado() + 1;
                id1 = id;

                String n = id + "";
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton1;
    private javax.swing.JRadioButton RadioBoton1;
    private javax.swing.JRadioButton RadioBoton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JTextField texto1;
    private javax.swing.JTextField texto2;
    private javax.swing.JTextField texto3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar() {
        int id = sujeto.getEstado() + 1;
                id1 = id;

                String n = id + "";
    }
}
